apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-proxy
spec:
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"