apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;
    events { worker_connections 1024; }

    http {
      log_format main '$remote_addr - $remote_user [$time_local] '
                      '"$request" $status $body_bytes_sent '
                      '"$http_referer" "$http_user_agent" '
                      '$ssl_client_s_dn $ssl_client_verify';

      access_log /var/log/nginx/access.log main;
      error_log /var/log/nginx/error.log warn;

      # Rate limiting
      limit_req_zone $binary_remote_addr zone=api_rate:10m rate=5r/s;

      server {
        listen 8000;
        listen 8001;

        # SSL Client Auth
        ssl_client_certificate /etc/nginx/certs/ca.crt;
        ssl_verify_client on;

        # Tendermint RPC (8000)
        location /tendermint {
          limit_req zone=api_rate burst=10 nodelay;
          proxy_pass https://bc-challenge.dev.x.x/api;
          proxy_ssl_server_name on;
        }

        # Cosmos RPC (8001)
        location /cosmos {
          limit_req zone=api_rate burst=10 nodelay;
          proxy_pass https://bc-challenge.dev.x.x/rpc;
          proxy_ssl_server_name on;
        }
      }
    }